# Generated by Django 3.1.2 on 2020-10-23 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cofuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=20)),
                ('departure_city', models.CharField(max_length=35)),
                ('arrival_city', models.CharField(max_length=35)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('covid_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=8)),
                ('covid_test', models.BooleanField()),
                ('test_results', models.CharField(max_length=3)),
                ('fever_chills', models.BooleanField()),
                ('cough', models.BooleanField()),
                ('breathing_issues', models.BooleanField()),
                ('aches', models.BooleanField()),
                ('headache', models.BooleanField()),
                ('loss_taste_smell', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('congestion', models.BooleanField()),
                ('nausea', models.BooleanField()),
                ('diarrhea', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='cofuser',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FlightsTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_seat', models.CharField(max_length=8)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flight')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.survey')),
            ],
        ),
    ]
