# Generated by Django 3.1.2 on 2020-10-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201023_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='test_results',
            field=models.CharField(default='N/A', max_length=3),
        ),
    ]
