# Generated by Django 3.1.2 on 2020-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201023_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='covid_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
